"""Compile CHANGELOG.md from change fragments (pure: fragments in, text out)."""

from __future__ import annotations

from collections.abc import Sequence

from footystreams.tools.changelog.fragment import ChangeType, Fragment, Impact

SECTION_TITLES: dict[ChangeType, str] = {
    ChangeType.ADDED: "Added",
    ChangeType.CHANGED: "Changed",
    ChangeType.FIXED: "Fixed",
    ChangeType.REMOVED: "Removed",
    ChangeType.DEPRECATED: "Deprecated",
    ChangeType.SECURITY: "Security",
    ChangeType.PERF: "Performance",
    ChangeType.REFACTOR: "Refactoring",
    ChangeType.TEST: "Tests",
    ChangeType.DOCS: "Documentation",
    ChangeType.BUILD: "Build and tooling",
}
HEADER = """# Changelog

> Generated by `uv run changelog build` from the fragments in `changes/`. **Do not edit by hand**:
> add a fragment with `uv run changelog new` instead (see `changes/README.md`).

Format: [Keep a Changelog](https://keepachangelog.com/). Versioning: SemVer for the project;
`SIM_VERSION` and `SCHEMA_VERSION` are versioned separately and recorded on every match.
"""


def render_changelog(unreleased: Sequence[Fragment]) -> str:
    """Render the whole CHANGELOG.md text."""
    sections = ["## [Unreleased]", *_render_sections(unreleased)]
    return HEADER + "\n" + "\n\n".join(sections) + "\n"


def _render_sections(fragments: Sequence[Fragment]) -> list[str]:
    if not fragments:
        return ["_No unreleased changes._"]
    rendered = []
    for change_type, title in SECTION_TITLES.items():
        members = sorted((f for f in fragments if f.type is change_type), key=lambda f: f.id)
        if members:
            lines = [_render_line(fragment) for fragment in reversed(members)]
            rendered.append("\n".join([f"### {title}", *lines]))
    return rendered


def _render_line(fragment: Fragment) -> str:
    notes = [fragment.milestone, "scope: " + ", ".join(fragment.scope)]
    for label, impact in (
        ("sim", fragment.sim_version_impact),
        ("schema", fragment.schema_version_impact),
    ):
        if impact is not Impact.NONE:
            notes.append(f"{label} version {impact}")
    flags = ("**BREAKING** " if fragment.breaking else "") + (
        "(migration needed) " if fragment.migration else ""
    )
    return f"- **{fragment.id}** {flags}{fragment.summary} *({'; '.join(notes)})*"
